### ISSUE TITLE
Writing a Complete Zone on the Actual Drive

### ISSUE THREAD

**Issue by Yash3667** [hgst/libzbc#12]
Hi,

I am trying to write an entire zone (256 MB) on an actual drive (not a fake one) and I am getting a "Cannot Allocate Memory (-12)" error. I am using the "zbc_write_zone" program.

The same does not happen if I write only 4 MB, and the interesting thing is that the program ends up writing 4 MB, 64 times. Hence, the total amount written is 256 MB. Yet, it gives an error if I write all 256 MB at once. Is this a bug or is this expected behavior?

Also, I get the same error "Cannot Allocate Memory (-12)" if I ever write more than 4 MB. Please find attached, the output from my terminal.

Note: This does not happen on a fake drive with emulation. I am able to write an entire zone without issue.

Thanks,

Yash
[SMRDriveTest.txt](https://github.com/hgst/libzbc/files/149034/SMRDriveTest.txt)

**Comment by hgst** [comment]
Hi Yash,

The "no memory" error is returned from within the SG_IO ioctl processing. This is likely due to a failure to allocate a kernel level buffer for an indirect I/O and/or failure to allocate a large enough vector of pages for the processing of the I/O.

A better strategy for I/Os, as you discovered, is to execute smaller operations in a loop. This of course could be implemented within zbc_read & zbc_write. However, libzbc functions are kept as simple as possible, that is, a single disk request whenever possible. Doing so, an application can control and handle errors more easily.

Implementing another simple library on top of libzbc, e.g. libzbc_io, would be an elegant solution to handle more efficiently "any size" I/O operation.

Best regards.

Damien Le Moal,
HGST / Western Digital

**Comment by Yash3667** [comment]
Hi Damien,

Yes, I found that looping over a zone and writing small number of bytes in each iteration works for me.

I have another question though. In my case, the limit for a single write is 4MB. Is this limit the same for all distributions of Linux, or is it enforced differently by Ubuntu than Fedora or Mint?

Also, considering that these drives use the sg driver for access, I assume that they would not work on other *nixes like FreeBSD or OS X. Am I correct in assuming so?

Thanks,
Yash

**Comment by hgst** [comment]
Hi Yash,

The maximum command size that can be reliably sent to a disk depends on many parameters:
1) The disk interface (SAS vs SATA)
2) The HBA being used (number of scatter/gather elements per command)
3) The architecture page size
4) The kernel version/configuration (maximum number of pages per BIO)
etc...

Since not all these parameters are hardware, yes, differences may appear between distributions due to kernel and drivers differences. An application can however determine a good maximum I/O size value by inspecting the values reported by the different files under /sys/block/<disk>/queue. Please refer to these files documentation for more information on their meaning.

As for the SG driver, since it has been ported to the xxxBSD family, libzbc should in principle work. But we have not done tests to verify this. As far as I know and can verify, OSX does not allow sending SCSI commands to a disk from userspace.

Best regards.

Damien Le Moal,
HGST / Western Digital
