### ISSUE TITLE
Error Reporting with Multi-Threaded I/O

### ISSUE THREAD

**Issue by TweakySolution** [hgst/libzbc#29]
Currently the `zbc_errno` struct is defined per device and is cleared / reset per I/O. When using async I/O to the same device, one runs the risk of losing critical sense key / sense code information.

I'm wondering if we can make `zbc_errno` thread local.

Alternatively, we could open multiple zbd device handles per I/O thread.

**Comment by TweakySolution** [comment]
I do not have a patch available - just scoping out the possibility for a multi-threaded approach to our software. If your schedule permits it please proceed. Otherwise let me know and I can look into it. Thanks.

**Comment by damien-lemoal** [comment]
I pushed a patch in the staging branch (rebased on top of master HEAD) to make the asc/ascq returned by zbc_errno() thread safe. Can you please check ? Everything looks good for me with zbc_tests but I have not specifically tested the multi-thread case. I need to write something for that. Since you seem to have a multi-thread application already, if you could test that would be great.
Once you confirm (please send my your Tested-by tag), I will push to master branch and make a new release.

**Comment by TweakySolution** [comment]
Confirmed using our multi-threaded driver.

Not sure how to tag the commit. I don't have permission to push to staging

**Comment by TweakySolution** [comment]
Tested-by: Nathaniel Roiger

**Comment by damien-lemoal** [comment]
Merged and released as 5.7.3. Thanks !
